### PR TITLE
Clean pequin submodule after run and simplify install 

### LINKED ISSUE #5: add shell scripts to automate steps in READMEs

### PR DESCRIPTION
**Pull request by jopasserat**
- [x] Dependencies build script and install to current directory
- [x] Adapt server's external process to run in submodule (no need to copy files)
- [x] Clean submodule on exit
- [x] gitignore
- [x] move readme instructions into scripts (fix #5 )
- [x] switch apps from command line

### CODE REVIEW

**Comment by gleim** [comment]
regarding coveai_server.js and the addition of work_dir - should work_dir be leveraged in the calls to ./bin/* and ./*.sh?  those calls appear to make assumptions about the current working directory which make work_dir redundant unless work_dir is completely leveraged, replacing ./.

**Comment by jopasserat** [comment]
As far as I understand node's `spawn` [function's doc](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) it is: it specifies the working dir from which the process is spawned (_Use cwd to specify the working directory from which the process is spawned. If not given, the default is to inherit the current working directory._) even though, the previous paragraphs mentions another behaviour (_cwd <string> Current working directory of the child process._). They are not incompatible and it seems both are correct.

If I remove the `./` when summoning the scripts or binaries I get: 

```
Error: spawn pepper_compile_and_setup_V.sh ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

and something similar if I leave the default `cwd`:

```
Error: spawn ./pepper_compile_and_setup_V.sh ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Or did you mean something totally different?

**Comment by gleim** [comment]
I believe I was (incorrectly) thinking that you would run this from compute_prover/server/ rather than from compute_prover/server/pequin/pepper.

**Comment by jopasserat** [comment]
yes you would. it's all based on the README assumptions of which directory you're meant to be located in (more commits commits in this direction). My statement from above holds when I start the node app using the `./run.sh` script from the `compute_prover/server` directory

**Comment by gleim** [comment]
looks like all of my comments on this Issue are incorrect, I have verified that what I thought may the correct approach does not work.

**Comment by jopasserat** [comment]
no worries, this was not super clear to me either, wouldn't call myself a node ninja :) 
just pushed a final commit to quickly switch apps from the command line
that should do for usability on my side

**Comment by gleim** [comment]
yes, all of this looks good.  currently testing your branch

**Pull request merged**
